version: "3.8"
services:
  train:
    image: prajyotrakh/registertrain:latest
    ports:
      - "82:80"
    deploy:
      replicas: 2       
  movie:
    image: prajyotrakh/registermovie:latest
    ports:
      - "82:80"
    deploy:
      replicas: 2      
  shop:
    image: prajyotrakh/registershop:latest 
    ports:
      - "84:80"
    deploy:
      replicas: 2        
